#!/usr/bin/env bash
# This script configures and starts Apache.

# Add ServerName to avoid Apache startup warnings
echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Start Apache in the background
service apache2 start

echo "apache2 is running"

